export const Types = {
  //ALL MODALS
  modalTypes: {
    TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
    TOGGLE_PROFILE_MODAL: "TOGGLE_PROFILE_MODAL",
    CLOSE_ALL: "CLOSE_ALL",
    TOGGLE_THOUGHT_MODAL: "TOGGLE_THOUGHT_MODAL",
    SET_THOUGHT_EDIT: "SET_THOUGHT_EDIT",
    DISPLAY_THOUGHT: "DISPLAY_THOUGHT",
  },
  // THOUGHT TYPES
  thoughtTypes: {
    UPDATE_CONTENT: "UPDATE_CONTENT",
  },
  // THOUGHT TO DISPLAY
  displayTypes: {
    SET_THOUGHT_TO_DISPLAY: "SET_THOUGHT_TO_DISPLAY",
    NEW_THOUGHT_ADDED: "NEW_THOUGHT_ADDED",
    DISPLAY_USER_THOUGHTS: "DISPLAY_USER_THOUGHTS",
  },
  // ALERT TYPES
  alertTypes: {
    SET_NEW_ALERT: "SET_NEW_ALERT",
    CLEAR_ALL_ALERTS: "CLEAR_ALL_ALERTS",
  },
  // LOADING TYPES
  loading: {
    SET_LOADING: "SET_LOADING",
    DISABLE_LOADING: "DISABLE_LOADING",
    LOGIN_LOADING: "LOGIN_LOADING",
    DISABLE_LOGIN_LOADING: "DISABLE_LOGIN_LOADING",
  },
  // THOUGHTS
  thoughts: {
    FECTH_NEW: "FECTH_NEW",
  },
  userTypes: {
    SET_USER: "SET_USER",
  },
};
