export const Types = {
  //ALL MODALS
  modalTypes: {
    TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
    TOGGLE_PROFILE_MODAL: "TOGGLE_PROFILE_MODAL",
    CLOSE_ALL: "CLOSE_ALL",
    TOGGLE_THOUGHT_MODAL: "TOGGLE_THOUGHT_MODAL",
  },
  // THOUGHT TYPES
  thoughtTypes: {
    UPDATE_TITLE: "UPDATE_TITLE",
    UPDATE_CONTENT: "UPDATE_CONTENT",
  },
  // ALERT TYPES
  alertTypes: {
    SET_NEW_ALERT: "SET_NEW_ALERT",
  },
};
